# Generated by Django 2.2.12 on 2020-04-08 09:05

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, default='없음', help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
