# Generated by Django 3.0.4 on 2020-03-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userribbon',
            name='where',
            field=models.CharField(choices=[('관리자 기본 지급', '관리자 기본 지급'), ('회원심사 리본 지급', '회원심사 리본 지급'), ('상위 10% 이성(무료)', '상위 10% 이성(무료)'), ('테마 소개 프로필 확인', '테마 소개 프로필 확인'), ('아만다 픽 프로필 확인', '아만다 픽 프로필 확인')], default='관리자 기본 지급', max_length=60),
        ),
    ]
