# Generated by Django 2.2.11 on 2020-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userribbon',
            name='where',
            field=models.CharField(choices=[(1, '아만다 픽 프로필 확인'), (2, '회원심사 리본 지급'), (3, '상위 10% 이성(무료)'), (4, '테마 소개 프로필 확인')], default='관리자 기본 지급', max_length=60),
        ),
    ]
