# Generated by Django 2.2.11 on 2020-04-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserInfo',
        ),
    ]
