# Generated by Django 2.2.11 on 2020-04-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectstory',
            name='story',
            field=models.CharField(blank=True, choices=[('1', '이상적인 첫 소개팅 장소'), ('내 외모중 가장 마음에 드는 곳은', '내 외모중 가장 마음에 드는 곳은'), ('남들보다 이것 하나는 자신있어요', '남들보다 이것 하나는 자신있어요')], max_length=60),
        ),
    ]
