# Generated by Django 2.2.11 on 2020-04-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200408_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userribbon',
            name='where',
            field=models.CharField(choices=[(0, '관리자 기본 지급'), (1, '아만다 픽 프로필 확인'), (2, '회원심사 리본 지급'), (3, '상위 10% 이성(무료)'), (4, '테마 소개 프로필 확인')], default=0, max_length=60),
        ),
    ]
