# Generated by Django 2.2.11 on 2020-04-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200402_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='personality',
        ),
    ]
