# Generated by Django 2.2.12 on 2020-04-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200414_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='personality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
