# Generated by Django 2.2.11 on 2020-04-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200404_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='img_profile',
            new_name='user_image',
        ),
    ]
