# Generated by Django 2.2.11 on 2020-04-03 04:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_userprofile_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blood_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AB형', 'AB형'), ('A형', 'A형'), ('B형', 'B형'), ('O형', 'O형')], max_length=30),
        ),
    ]
