# Generated by Django 2.2.12 on 2020-04-11 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200411_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.TagType'),
        ),
    ]
