# Generated by Django 2.2.11 on 2020-04-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200404_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='personality',
            field=models.CharField(blank=True, choices=[('지적인', '지적인'), ('차분한', '차분한'), ('유머있는', '유머있는'), ('낙천적인', '낙천적인'), ('내향적인', '내향적인'), ('외향적인', '외향적인'), ('감성적인', '감성적인'), ('상냥한', '상냥한'), ('귀여운', '귀여운'), ('섹시한', '섹시한'), ('4차원인', '4차원인'), ('발랄한', '발랄한'), ('도도한', '도도한')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
