# Generated by Django 2.2.11 on 2020-04-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200408_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userribbon',
            name='where',
            field=models.CharField(choices=[(1, '관리자 기본 지급'), (2, '아만다 픽 프로필 확인'), (3, '회원심사 리본 지급'), (4, '상위 10% 이성(무료)'), (5, '테마 소개 프로필 확인')], default=1, max_length=60),
        ),
    ]
