# Generated by Django 2.2.12 on 2020-04-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200411_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendstar',
            name='star',
            field=models.PositiveIntegerField(max_length=30),
        ),
    ]
