# Generated by Django 2.2.11 on 2020-04-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200404_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userribbon',
            name='ribbon',
            field=models.PositiveIntegerField(default='10'),
        ),
    ]
