# Generated by Django 2.2.11 on 2020-04-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200405_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='user_image',
            new_name='image',
        ),
    ]
