# Generated by Django 2.2.11 on 2020-04-03 04:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200403_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personality',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('지적인', '지적인'), ('차분한', '차분한'), ('유머있는', '유머있는'), ('낙천적인', '낙천적인'), ('내향적인', '내향적인'), ('외향적인', '외향적인'), ('감성적인', '감성적인'), ('상냥한', '상냥한'), ('귀여운', '귀여운'), ('섹시한', '섹시한'), ('4차원인', '4차원인'), ('발랄한', '발랄한'), ('도도한', '도도한')], default='', max_length=57),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('AB형', 'AB형'), ('A형', 'A형'), ('B형', 'B형'), ('O형', 'O형')], max_length=30),
        ),
    ]
