# Generated by Django 2.2.11 on 2020-04-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200404_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userribbon',
            name='ribbon',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
