# Generated by Django 2.2.11 on 2020-04-06 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200406_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='star_users',
        ),
        migrations.AddField(
            model_name='user',
            name='like_users',
            field=models.ManyToManyField(related_name='send_me_like_users', through='members.SendLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='star_users',
            field=models.ManyToManyField(related_name='send_me_star_users', through='members.SendStar', to=settings.AUTH_USER_MODEL),
        ),
    ]
