# Generated by Django 2.2.11 on 2020-04-03 05:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200403_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecttag',
            name='charm',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('고기를 잘 구워요', '고기를 잘 구워요'), ('커리어 중요해요', '커리어 중요해요')], max_length=60),
        ),
        migrations.AlterField(
            model_name='selecttag',
            name='date_style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('인스타감성 카페가기', '인스타감성 카페가기'), ('퇴근 후 치맥하기', '퇴근 후 치맥하기')], max_length=60),
        ),
        migrations.AlterField(
            model_name='selecttag',
            name='life_style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('패션에 관심 많아요', '패션에 관심 많아요'), ('여행 자주 가요', '여행 자주 가요')], max_length=60),
        ),
        migrations.AlterField(
            model_name='selecttag',
            name='relationship_style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('연상이 좋아요', '연상이 좋아요'), ('연상보다 연하', '연상보다 연하')], max_length=60),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personality',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('지적인', '지적인'), ('차분한', '차분한'), ('유머있는', '유머있는'), ('낙천적인', '낙천적인'), ('내향적인', '내향적인'), ('외향적인', '외향적인'), ('감성적인', '감성적인'), ('상냥한', '상냥한'), ('귀여운', '귀여운'), ('섹시한', '섹시한'), ('4차원인', '4차원인'), ('발랄한', '발랄한'), ('도도한', '도도한')], max_length=57),
        ),
    ]
