# Generated by Django 2.2.11 on 2020-03-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200329_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='body_shape',
        ),
        migrations.RemoveField(
            model_name='user',
            name='drinking',
        ),
        migrations.RemoveField(
            model_name='user',
            name='introduce',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='major',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='personality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.RemoveField(
            model_name='user',
            name='smoking',
        ),
        migrations.RemoveField(
            model_name='user',
            name='star_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tall',
        ),
        migrations.CreateModel(
            name='UserSpecific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=60, unique=True)),
                ('job', models.CharField(blank=True, max_length=50)),
                ('school', models.CharField(blank=True, max_length=50)),
                ('age', models.CharField(blank=True, choices=[('20', 20), ('21', 21), ('22', 22), ('23', 23), ('24', 24), ('25', 25), ('26', 26), ('27', 27), ('28', 28), ('29', 29), ('30', 30), ('31', 31), ('32', 32), ('33', 33), ('34', 34), ('35', 35), ('36', 36), ('37', 37), ('38', 38), ('39', 39), ('40', 40), ('41', 41), ('42', 42), ('43', 43), ('44', 44), ('45', 45), ('46', 46), ('47', 47), ('48', 48), ('49', 49)], max_length=10)),
                ('region', models.CharField(blank=True, choices=[('서울', '서울'), ('경기', '경기'), ('인천', '인천'), ('대전', '대전'), ('충북', '충북'), ('충남', '충남'), ('강원', '강원'), ('부산', '부산'), ('경북', '경북'), ('경남', '경남'), ('대구', '대구'), ('울산', '울산'), ('광주', '광주'), ('전북', '전북'), ('전남', '전남'), ('제주', '제주')], max_length=30)),
                ('body_shape', models.CharField(blank=True, choices=[('보통체형', '보통체형'), ('통통한', '통통한'), ('살짝볼륨', '살짝볼륨'), ('글래머', '글래머'), ('마른', '마른'), ('슬림탄탄', '슬림탄탄')], max_length=50)),
                ('introduce', models.CharField(blank=True, max_length=150)),
                ('major', models.CharField(blank=True, max_length=50)),
                ('tall', models.CharField(blank=True, choices=[('140', 140), ('141', 141), ('142', 142), ('143', 143), ('144', 144), ('145', 145), ('146', 146), ('147', 147), ('148', 148), ('149', 149), ('150', 150), ('151', 151), ('152', 152), ('153', 153), ('154', 154), ('155', 155), ('156', 156), ('157', 157), ('158', 158), ('159', 159), ('160', 160), ('161', 161), ('162', 162), ('163', 163), ('164', 164), ('165', 165), ('166', 166), ('167', 167), ('168', 168), ('169', 169), ('170', 170), ('171', 171), ('172', 172), ('173', 173), ('174', 174), ('175', 175), ('176', 176), ('177', 177), ('178', 178), ('179', 179), ('180', 180), ('181', 181), ('182', 182), ('183', 183), ('184', 184), ('185', 185), ('186', 186), ('187', 187), ('188', 188), ('189', 189), ('190', 190), ('191', 191), ('192', 192), ('193', 193), ('194', 194), ('195', 195), ('196', 196), ('197', 197), ('198', 198), ('199', 199)], max_length=10)),
                ('personality', models.CharField(blank=True, choices=[('지적인', '지적인'), ('차분한', '차분한'), ('유머있는', '유머있는'), ('낙천적인', '낙천적인'), ('내향적인', '내향적인'), ('외향적인', '외향적인'), ('감성적인', '감성적인'), ('상냥한', '상냥한'), ('귀여운', '귀여운'), ('섹시한', '섹시한'), ('4차원인', '4차원인'), ('발랄한', '발랄한'), ('도도한', '도도한')], max_length=50)),
                ('blood_type', models.CharField(blank=True, choices=[('AB형', 'AB형'), ('A형', 'A형'), ('B형', 'B형'), ('O형', 'O형')], max_length=30)),
                ('drinking', models.CharField(blank=True, choices=[('가끔 마심', '가끔 마심'), ('어느정도 즐기는편', '어느정도 즐기는편'), ('술자리를 즐김', '술자리를 즐김'), ('마시지 않음', '마시지 않음')], max_length=60)),
                ('smoking', models.CharField(blank=True, choices=[('흡연', '흡연'), ('비흡연', '비흡연')], max_length=60)),
                ('like_users', models.ManyToManyField(related_name='send_me_like_users', through='members.SendLike', to='members.UserSpecific')),
                ('star_users', models.ManyToManyField(related_name='send_me_star_users', through='members.SendStar', to='members.UserSpecific')),
            ],
        ),
    ]
