# Generated by Django 2.2.11 on 2020-04-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200406_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='religion',
            field=models.CharField(blank=True, choices=[('종교 없음', '종교 없음'), ('기독교', '기독교'), ('천주교', '천주교'), ('불교', '불교'), ('원불교', '원불교'), ('유교', '유교'), ('이슬람교', '이슬람교')], max_length=60),
        ),
    ]
