# Generated by Django 2.2.12 on 2020-04-11 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200411_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_users',
        ),
        migrations.DeleteModel(
            name='SendLike',
        ),
        migrations.AddField(
            model_name='sendpick',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_sendpick_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sendpick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sendpick_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='pick_users',
            field=models.ManyToManyField(related_name='send_me_pick_users', through='members.SendPick', to=settings.AUTH_USER_MODEL),
        ),
    ]
