# Generated by Django 2.2.11 on 2020-04-07 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_userinfo_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userribbon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
