# Generated by Django 2.2.11 on 2020-04-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20200407_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userribbon',
            name='ribbon',
        ),
        migrations.AddField(
            model_name='userribbon',
            name='paid_ribbon',
            field=models.IntegerField(default=10),
        ),
    ]
